export const PopupActionTypes = {
    SET_WINDOW_ALERT: "SET_WINDOW_ALERT",
    SET_WINDOW_CONFIRM: "SET_WINDOW_CONFIRM",
    SET_REQUEST_TIMEOUT_ALERT: "SET_REQUEST_TIMEOUT_ALERT",
    SET_REQUEST_ERROR_ALERT: "SET_REQUEST_ERROR_ALERT",
    SET_WARNING_ALERT: "SET_WARNING_ALERT",
    SET_QUESTION_CONFIRM: "SET_QUESTION_CONFIRM",
    CLOSE_POPUP: "CLOSE_POPUP",
};
