export const RequestActionTypes = {
    SET_TOKEN: "SET_TOKEN",
    CLEAR_TOKEN: "CLEAR_TOKEN",
    REQUEST_STARTED: "REQUEST_STARTED",
    REQUEST_FINISHED: "REQUEST_FINISHED",
    REQUEST_FAILED: "REQUEST_FAILED",
};
